const TYPES = [
    'Appearance or Signing',
    'Attraction',
    'Camp, Trip or Retreat',
    'Class, Training or Workshop',
    'Concert or Performance',
    'Conference',
    'Convention',
    'Dinner or Gala',
    'Festival or Fair',
    'Game or Competition',
    'Meeting or Networking Event',
    'Other',
    'Party or Social Gathering',
    'Race or Endurance Event',
    'Rally',
    'Screening',
    'Seminar or Talk',
    'Tour',
    'Tournament',
    'Tradeshow, Consumer Show or Expo',
];
const CATEGORIES = [
    'Auto, Boat & Air',
    'Business & Professional',
    'Charity & Causes',
    'Community & Culture',
    'Family & Education',
    'Fashion & Beauty',
    'Film, Media & Entertainment',
    'Food & Drink',
    'Government & Politics',
    'Health & Wellness',
    'Hobbies & Special Interest',
    'Home & Lifestyle',
    'Music',
    'Other',
    'Performing & Visual Arts',
    'Religion & Spirituality',
    'School Activities',
    'Science & Technology',
    'Seasonal & Holiday',
    'Sports & Fitness',
    'Travel & Outdoor',
];
const LANGUAGES = [
    'Bengali',
    'English',
    'French',
    'German',
    'Hindi',
    'Japanese',
    'Korean',
    'Mandarin Chinese',
    'Marathi',
    'Spanish',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Telugu',
    'Turkish',
    'Vietnamese',
    'Wu Chinese',
];

export { TYPES, CATEGORIES, LANGUAGES };
