import EVENTS_QUERY from './events';
import EVENT_BY_ID_QUERY from './eventById';
import EVENTS_BY_PARAM_QUERY from './eventsByParam';
import USER_DATA_QUERY from './userData';
import TICKET_SALES_BY_EVENT_IDS_QUERY from './ticketSalesByEventId';
import TICKETS_FOR_EVENTS_BY_ACCOUNT_NAME_QUERY from './ticketsForEventsByAccountName';
import COLLECTIONS_BY_ACCOUNT_NAME_QUERY from './collectionsByAccountName';
import TICKET_BY_ASSET_ID_QUERY from './ticketByAssetId';
import EVENTS_BY_IDS_QUERY from './eventsByIds';
import EVENTS_BY_CREATOR_QUERY from './eventByCreator';
import TICKETS_SALES_BY_ACCOUNT_NAME_QUERY from './ticketsSalesByAccountName';
import TICKET_SCHEMAS_BY_ACCOUNT_NAME_AND_COLLECTION_NAME_QUERY from './ticketSchemasByAccountNameAndCollectionName';
import TICKET_TEMPLATES_BY_EVENT_ID_QUERY from './ticketTemplatesByEventId';

export {
    EVENT_BY_ID_QUERY,
    EVENTS_QUERY,
    EVENTS_BY_PARAM_QUERY,
    USER_DATA_QUERY,
    TICKETS_FOR_EVENTS_BY_ACCOUNT_NAME_QUERY,
    COLLECTIONS_BY_ACCOUNT_NAME_QUERY,
    TICKET_BY_ASSET_ID_QUERY,
    EVENTS_BY_IDS_QUERY,
    EVENTS_BY_CREATOR_QUERY,
    TICKET_SALES_BY_EVENT_IDS_QUERY,
    TICKETS_SALES_BY_ACCOUNT_NAME_QUERY,
    TICKET_SCHEMAS_BY_ACCOUNT_NAME_AND_COLLECTION_NAME_QUERY,
    TICKET_TEMPLATES_BY_EVENT_ID_QUERY,
};
