export const EVENT_LANGUAGES = [
    'Bengali',
    'English',
    'French',
    'German',
    'Hindi',
    'Japanese',
    'Korean',
    'Mandarin Chinese',
    'Marathi',
    'Spanish',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Telugu',
    'Turkish',
    'Vietnamese',
    'Wu Chinese',
];
